### ISSUE TITLE
Argument 1 passed to TYPO3\HtmlSanitizer\Behavior\Tag::addAttrs() must be of the type array, object given

### ISSUE THREAD

**Issue by TTpfel** [TYPO3/html-sanitizer#107]
Hello, I have no idea if I'm at the right place here or if this should be posted in the TYPO3 forge. Sorry if I'm wrong here.

I'm using an ELTS Version of TYPO3 8 with PHP 7.4.33 for my website. Since the 8.7.49 update I can't view any pages in the frontend or backend (page & list module) with the error 
`Argument 1 passed to TYPO3\HtmlSanitizer\Behavior\Tag::addAttrs() must be of the type array, object given, called in /var/www/html/src/vendor/typo3/cms/typo3/sysext/core/Classes/Html/DefaultSanitizerBuilder.php on line 75`.

The [release notes of that version](https://get.typo3.org/release-notes/8.7.49) show an upgrade to v.1.5.0 of the HTML-Sanitizer.

I'm not well-versed in anything programming related but opening the file from the error gives the following warning in PHPStorm:
`Expected parameter of type '\TYPO3\HtmlSanitizer\Behavior\Attr[]', '\TYPO3\HtmlSanitizer\Behavior\Attr' provided`

If I add back the removed brackets in the createBasicTags() and build() functions of the DefaultSanitizerBuilder class everything works again:
``` 
        return GeneralUtility::makeInstance(Sanitizer::class, $visitor);

        $tags['a']->addAttrs(
            (new Behavior\Attr('onclick'))
                ->addValues(new Behavior\RegExpAttrValue('#^openPic\(#'))
        );
```
turns into 
```
        return GeneralUtility::makeInstance(Sanitizer::class, [$visitor]);

        $tags['a']->addAttrs([
            (new Behavior\Attr('onclick'))
                ->addValues(new Behavior\RegExpAttrValue('#^openPic\(#'))
        ]);
```

The return statement still shows the warning
`Return value is expected to be '\TYPO3\HtmlSanitizer\Sanitizer', 'object|\TYPO3\CMS\Core\SingletonInterface' returned `
but the frontend and backend load again.

Turning off the sanitizer via TypoScript also "fixes" the error.

I've searched in the forge and on other sites but couldn't find anyone with the same issue, but I feel like this is an issue directly in TYPO3 or the sanitizer and not in the environment.

**Comment by andreasfernandez** [comment]
Hello.

Can you please describe the setup of your project? Do you have a Composer-based setup or do you use the "classic" packages?

**Comment by ohader** [comment]
> I'm using an ELTS Version of TYPO3 8 with PHP 7.4.33 for my website. Since the 8.7.49 update I can't view any pages in the frontend or backend (page & list module) with the error `Argument 1 passed to TYPO3\HtmlSanitizer\Behavior\Tag::addAttrs() must be of the type array, object given, called in /var/www/html/src/vendor/typo3/cms/typo3/sysext/core/Classes/Html/DefaultSanitizerBuilder.php on line 75`.
> 
> The [release notes of that version](https://get.typo3.org/release-notes/8.7.49) show an upgrade to v.1.5.0 of the HTML-Sanitizer.

@TTpfel It seems that you're still using an old `1.0.x` Version of `typo3/html-sanitizer`, instead of `1.5.x`. With TYPO3 `v8.7.49` it is required to use `typo3/html-sanitizer:^1.5.0`.

### v1.0.7 expects `array`

`public function addAttrs(array $attrs)`
https://github.com/TYPO3/html-sanitizer/blob/v1.0.7/src/Behavior/Tag.php#L82

## v1.5.0 expects variadic `Attr`

`public function addAttrs(Attr ...$attrs): self`
https://github.com/TYPO3/html-sanitizer/blob/v1.5.0/src/Behavior/Tag.php#L80

**Comment by TTpfel** [comment]
> Can you please describe the setup of your project? Do you have a Composer-based setup or do you use the "classic" packages?

It's composer based, after checking which version of the sanitizer is installed `"minimum-stability": "dev"` turned out to be the culprit.

When dev is set as minimum stability `v1.x-dev` gets downloaded by composer if `^1.5.0` is specified.
`Updating typo3/html-sanitizer (v1.5.0 => v1.x-dev):`

`typo3/cms` required `^1.5.0` and composer automatically installed `v1.x-dev`.

I've changed the minimum stability to stable and everything works as expected.

Thank you for the fast help!
