### ISSUE TITLE
Figure tag is missing and source tag does not allow necessary attributes

### ISSUE THREAD

**Issue by kevin-appelt** [TYPO3/html-sanitizer#16]
The source tag does not allow the needed attributes, but only the global ones.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source#attributes

The figure tag is missing completely.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element#text_content
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure

**Comment by Neowar** [comment]
This problem also occurs in 8.7.42 and also affects normal script tags in a Fluid template (not included via TypoScript rendering or with f:format.html). And over all our projects.

**Comment by Jashi** [comment]
Is this an implicit or explicit parseFunc call (cause we are not explicitly using this anywhere).

**Comment by Jashi** [comment]
So is there a recommended way to fix TYPO3 forms (added as form_formframework element in the BE) or custom content elements then? Those are the ones that break for us.

**Comment by ohader** [comment]
I've updated documentation a bit - maybe that helps already
* https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Important-94484-IntroduceHTMLSanitizer.html#troubleshooting
* https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.5.x/Important-94484-IntroduceHTMLSanitizer.html#debugging-logging

In case it does not, the actual use-case would have to be analyzed (to be honest, I don't know what happens internally in `ext:form` for this particular scenario).

**Comment by darthnorman** [comment]
For us it really was <f:format.html> in a bunch of page templates where we didn't want any escaping, so we changed some of them to <f:format.raw>

**Comment by georgringer** [comment]
> For us it really was <f:format.html> in a bunch of page templates where we didn't want any escaping, so we changed some of them to <f:format.raw>

just as FYI: this won't convert e.g. links anymore

**Comment by ohader** [comment]
> > For us it really was <f:format.html> in a bunch of page templates where we didn't want any escaping, so we changed some of them to <f:format.raw>
> 
> just as FYI: this won't convert e.g. links anymore

Example: `<a href="t3://...">` is not resolved to the actual page, resource, ... anymore when using `f:format.raw`, that substitution happened in `parseFunc` which was used by `f:format.html`.

**Comment by matin73** [comment]
page.10.stdWrap.parseFunc.htmlSanitize = 0
lib.parseFunc_RTE.htmlSanitize = 0
lib.parseFunc.htmlSanitize = 0

all not working - html elements for e. <script> and also normal content elements with images <figure> are broken. Solution realy needed!

**Comment by ohader** [comment]
> are broken. Solution realy needed!

Which TYPO3 version are you referring to?

**Comment by matin73** [comment]
> 
> 
> > all not working - html elements for e. <script> and also normal content elements with images
> 
> In case ALL TAGS of your website are "broken" (= sanitized), then there surely is some invocation of either `parseFunc` in TypoScript or `f:format.html` in Fluid on very top level during the rendering process.
> 
> > are broken. Solution realy needed!
> 
> Which TYPO3 version are you referring to?

TYPO3 10.4.19

**Comment by sportsocke** [comment]
Same problem here with 10.4.19 

All <figure> code from the normal image contentelement aren't working.. are html contentelements aren't working.. and the form plugin too.


<img width="798" alt="Bildschirmfoto 2021-08-11 um 14 05 45" src="https://user-images.githubusercontent.com/49714627/129025650-b8c982e9-c269-4aa0-a3b8-aad8c728000d.png">

**Comment by rvkammen** [comment]
We encountered the issue with the <f:format.html aswell. In our case it is with form elements.
Did some debugging (TYPO3 10) and it seems like the issue is in TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::parseFunc

Made a bug report for this too. Perhaps this helps in solving the issue: https://forge.typo3.org/issues/94810
The same also happend in a 7.6 ELTS version but have not debugged this. So not sure if its the same.

**Comment by ohader** [comment]
# ℹ️ Notice

It's getting a little bit chaotic here - thus, I've compiled on [overview for troubleshooting ](https://github.com/TYPO3/html-sanitizer/issues/23). Please have a look first before creating new issues. Thanks!

**Comment by ohader** [comment]
I think we're done here.

Find tracking at https://forge.typo3.org/issues/94787
Feel free to ask in [TYPO3 Slack Channel](https://typo3.org/community/meet/how-to-use-slack-in-the-typo3-community) for `#typo3-cms` for further support.

**Comment by m-kappenberg** [comment]
Is it possible to add "features" like this in future with working global options like:
config.enableHtmlSanitizer = 1
and not "eat or die, rework all parseFunc implementations... "?
+TYPO3 Version number, breaking change in FE rendering?
Have a scenario like this in mind:
Contract with customer... having always latest updates... on a large website (50K ++ sites)
calc workload for a change like this.

**Comment by ohader** [comment]
@m-kappenberg There is a feature flag `security.frontend.htmlSanitizeParseFuncDefault` in pending patch:
https://review.typo3.org/c/Packages/TYPO3.CMS/+/70404/8/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php#3364

However, the focus still is to make TYPO3 secure per default - `security.frontend.htmlSanitizeParseFuncDefault` just defines the default values in case neither `htmlSanitize = 0` or `htmlSanitize = 1` was given.

**Comment by RonaldKools** [comment]
@matin73 the new Typo3 9.5.30 update fixed all `<f:format.html parseFuncTSPath="">` issues for me. 

Thanx @ohader , keep up the good work!
