### ISSUE TITLE
Mailto doesn't work if used with spamProtectEmailAddresses

### ISSUE THREAD

**Issue by MiladinBojic** [TYPO3/html-sanitizer#20]
With htmlSanitize mailto attribute is enabled, but if we have 
config.spamProtectEmailAddresses = 1
then the generated tag looks like this:
`<a href="javascript:linkTo_UnCryptMailto('ocknvq,hqqBdct0vnf');">foo(at)bar.tld</a>`

The tag is generated before of sanitizing, and so the attribute href is being removed.

**Comment by ohader** [comment]
Thanks for your report. Since this is a TYPO3 CMS specific question (and this package is generic), it is handled on forge.typo3.org.

→ please see https://forge.typo3.org/issues/94776
