### ISSUE TITLE
Attribute "loading" missing for <img>-tag

### ISSUE THREAD

**Issue by schlotzz** [TYPO3/html-sanitizer#24]
The "loading"-attribute should not be filtered for `<img>`-tags.
see pull request #22

**Comment by ohader** [comment]
Thanks for your report. Please have a look the [troubleshooting issue](https://github.com/TYPO3/html-sanitizer/issues/23) as well. I guess the `<img loading="lazy">` attribute is not coming directly from a rich-text input field, but is generated in TypoScript or Fluid instead.

**Comment by schlotzz** [comment]
Thanks for your fast answer.
Inserting `htmlSanitize = 0` as proposed in your troubleshooting guide didn't work at all for me (TYPO3 v10.4.19). The `<figure>` tag is generated via a `FLUIDTEMPLATE`.

**Comment by ohader** [comment]
Ok, so the `<figure>` tag is encode somewhere during the rendering process - it probably is wrapped in some `<f:format.html>` instruction in Fluid templates, partials or layouts.

Besides that, are you using any "special" extensions for rendering content, like `gridelements`, `flux`, `vhs`, ... these kind of extensions that kick in on a global level?

**Comment by schlotzz** [comment]
The extension `gridelements` is used, but the affected content element has not been placed inside a `gridelements`-block. For testing purposes, the extension had been disabled but didn't affect the described behaviour - as expected.

Finally I could track down the unwanted behaviour to a `<f:format.html>` in my fluid-template. Replacing it with `<f:format.raw>` solved my problems.

Thanks for your help and the effort you put into this.

Anyway, shouldn't `<img loading="lazy">` be allowed, even if not generated directly from a RTE input? Just asking... ;-)

**Comment by ohader** [comment]
Closed PR #22, relevant changes were incorporated into PR #17.
I was holding back these `<figure>`, `<source>`, ... related changes to actually find the root cause that triggered HTML sanitizer in the first place. Anyway, it is not wrong to add those tags and attributes to this library.
