### ISSUE TITLE
TYPO3 HTML Element doesn't work anymore

### ISSUE THREAD

**Issue by intertain** [TYPO3/html-sanitizer#34]
The TYPO3 standard HTML content element uses `<f:format.raw>{data.bodytext}</f:format.raw>` . 

We have inserted iframes like this:
`<iframe id="auto-iframe" name="auto-iframe" src="https://lademap.ladenetz.de/?lat=48.3434118&amp;lng=10.8921117&amp;zoom=12&amp;mode=1&amp;ivin=09ut249ugn9854h8bffd43" scrolling="no" onload="AutoiFrameAdjustiFrameHeight('auto-iframe',50);" width="100%" height="650px" frameborder="0"></iframe>`

But since last T3 update it is shown plain in FE. 

I tried:
```
page.10.stdWrap.parseFunc {
    // replace --- with soft-hyphen
    short.--- = &shy;
    // sanitization of ALL MARKUP is NOT DESIRED here
    htmlSanitize = 0
  }

// either disable globally
lib.parseFunc.htmlSanitize = 0
lib.parseFunc_RTE.htmlSanitize = 0
```

But it ist not fixed. Could you please tell me how to get it work now without htmlSanitze?

Yours,
mike

**Comment by intertain** [comment]
I also tried to create an own Mask Element with Iframe code in the template, but also this is rendered in FE as plain text. How to deactivate htmlSanitizer? <f:format.row>... doesn't work. It very bad, that a minor T3 Update crashes running live sites... normally that shouldn't happen...

**Comment by ohader** [comment]
Which TYPO3 version are you using? Somewhere in your rendering instructions, there's an additional `<f:format.html>` or `stdWrap.parseFunc` call which activating sanitization. You'll find more info in https://github.com/TYPO3/html-sanitizer/issues/23.

With https://forge.typo3.org/issues/94837 debugging capabilities have been extended and would allow to get a debug stack-trace or corresponding invocation.

**Comment by ohader** [comment]
> Normally a minor T3 Update should not be able to crash running live sites... normally that shouldn't happen...

Well, I personally feel sorry about that... but I'm just a little, tiny part in that while TYPO3 eco-system. I cannot solve that all alone. And unfortunately, it is like that - lots of site had problems with the update - but on the other side, there also have been lots of sites that did not have these kind of trouble with their HTML templates and rendering process.

**Comment by ohader** [comment]
I think we're done here.

Find tracking at https://forge.typo3.org/issues/94787
Feel free to ask in [TYPO3 Slack Channel](https://typo3.org/community/meet/how-to-use-slack-in-the-typo3-community) for `#typo3-cms` for further support.
