### ISSUE TITLE
Links split up and rendered wrong with images and short texts

### ISSUE THREAD

**Issue by aaxc** [TYPO3/html-sanitizer#51]
Hey, I'm having issues with TYPO3 HTML rendering in version 10.
Every time there is an image inside a href with little text, it splits them apart, thus destroying the link:

Original
```html
<p>TITLE <em>ITALIC TEXT</em> basic text
<a href="PDF_LINK">→<img alt="" data-htmlarea-file-uid="1787699" src="pdf_icon.png" /></a>
</p>
```

f:format.html output
```html
<p>TITLE <em>ITALIC TEXT</em> basic text
<a href="PDF_LINK" target="_blank"></a>
</p>
<p>→<img src="pdf_icon.png"></p>
```

I tried Slack and also read this chain of issues (https://github.com/TYPO3/html-sanitizer/issues/23), but the problem still persists.

I can swap to raw, as there are typo3 internal links, that have to be rendered, and all the possible solutions either swapped to raw and broke internal links, or did nothing.

I'm running TYPO3 v10.4.20 with html-sanitizer v2.0.9
It's also a fresh update from v9.

**Comment by ohader** [comment]
Hm... `<img alt="" data-htmlarea-file-uid="1787699" src="pdf_icon.png" />` actually does not reference a valid image and seems to be a left-over "old RteHtmlArea times".

* handling of `data-htmlarea-file-uid` has been dropped in TYPO3 v10.0
  + https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-88500-RTEImageHandlingFunctionalityDropped.html
  + https://review.typo3.org/c/Packages/TYPO3.CMS/+/60886
* extracting/replacing those image references can be done with `rte_ckeditor_image`
  + https://extensions.typo3.org/extension/rte_ckeditor_image

Thus, I'm pretty sure the same issue would have happened without `typo3/html-sanitizer`.

**Comment by ohader** [comment]
Passing that HTML through `typo3/html-sanitizer` just slightly modifies the `alt` attribute (which seems to be a side-effect of the underlying parser - not checked/verified). However, the rest stayed the same:

```
Expected :'<p>TITLE <em>ITALIC TEXT</em> basic text <a href="PDF_LINK">→<img alt="" data-htmlarea-file-uid="1787699" src="pdf_icon.png" /></a></p>'
Actual   :'<p>TITLE <em>ITALIC TEXT</em> basic text <a href="PDF_LINK">→<img alt data-htmlarea-file-uid="1787699" src="pdf_icon.png"></a></p>'
```

**Comment by aaxc** [comment]
Hey, thank you for the quick response.

The system has been live for years and started with TYPO3 v4, so there is definately a lot of older stuff there.

I tried removing some data-htmlarea-file-uid from the editor, but it didnt change anything. It still moved the image (with text) outside the <a> tag for some reason, wich makes the link unclickable and without a cointent :/

**Comment by ohader** [comment]
> Also, if parsing just modifies the alt tag, what causes the text and image to be seperated from the `<a>` tag?

That `alt` attr change seems to be related to https://github.com/Masterminds/html5-php/issues/184 (however, that's just a side-effect, not really the problem here).

I tested the given markup again (replaced `PDF_LINK` with a real URI) in TYPO3 v10.4.20 with `fluid_styled_content` and `ext:bootstrap_package`, but could not verify the behavior you described.

Did you investigate, whether the same scenario did work in TYPO3 v10.4.18 (before `typo3/html-sanitizer` has been introduced)?

**Comment by aaxc** [comment]
Unfortunately this is not possible, since, as I mentioned, I just updated it during the weeking directly from v9 to v10.4.20.

I could try downgrading it though, just need to check if there are no system breaking changes.

**Comment by aaxc** [comment]
I did not downgrade, but adding `lib.parseFunc_RTE.htmlSanitize = 0` to global TS file helped

**Comment by ohader** [comment]
Thx for your feedback. In case you experience more aspect, feel free to create a new issue at https://forge.typo3.org/projects/typo3cms-core/issues - as it seems to be more a TypoScript settings topic.
