### ISSUE TITLE
Add support for [type], [start] and [reversed] attributes for the ol tag

### ISSUE THREAD

**Issue by YanickRoss** [TYPO3/html-sanitizer#56]
Hi,

we use the ordered bullet lists on our site, I know we can use the CSS "list-style-type" property to do the equivalent but for accessibility needs we have to use the [type], [start] and [reversed] attributes.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol

Thank you

**Comment by ohader** [comment]
Thx for the report. Seems to be reasonable, I'm going to have look into that during the next few days...

**Comment by ohader** [comment]
@YanickRoss do the changes as provided in PR #58 meet your requirements? Thx for your feedback!

**Comment by YanickRoss** [comment]
@ohader yes that's exactly what we want. thank you
