### ISSUE TITLE
Add different protocols for href such as webcal or ftp

### ISSUE THREAD

**Issue by clivebeckett** [TYPO3/html-sanitizer#57]
I use links like `webcal://domain.tld/calendar/ics` for having the OS open a calendar app like Apple Calendar and offer the calendar subscription dialogue. For those links the href gets stripped from the output HTML.

It would be great to add various other common protocols like e.g. `webcal`, `ftp`, `file` or at least offer a simple configuration method to add these to a website instead of having to add a complicated PHP class _(not to mention that at this point in time I have found a tutorial on how to allow additional tags and attributes, but not a different link protocol)._

**Comment by ohader** [comment]
@clivebeckett I've refactored URI assignment a bit and allowed additional schemes for `href` attributes (basically used for links). Please have a look at PR #60 and let me know whether that would work for your scenario. Thanks in advance!

**Comment by clivebeckett** [comment]
> @clivebeckett I've refactored URI assignment a bit and allowed additional schemes for `href` attributes (basically used for links). Please have a look at PR #60 and let me know whether that would work for your scenario. Thanks in advance!

Looks great to me! I am not as advanced a developer to be able to test this, though :) Thanks a lot for quickly adding the enhancement.

**Comment by ohader** [comment]
New TYPO3 v9 & v10 LTS maintenance releases are scheduled for today - so, I just wanted to have this change included there... 😉
