### ISSUE TITLE
tx_form_formframework not working in TYPO3 11

### ISSUE THREAD

**Issue by matin73** [TYPO3/html-sanitizer#61]
TYPO3 extension form not showing correct/broken if use <f:format.html parseFuncTSPath="">:

&lt;form enctype="multipart/form-data" method="post" id="kontaktformular-50" action="/kontakt?tx_form_formframework%5Baction%5D=perform&amp;amp;tx_form_formframework%5Bcontroller%5D=FormFrontend&amp;amp;cHash=d158ca0e601ac70a3252a9e6aa169797#kontaktformular-50"&gt;
&lt;div&gt;&lt;input type="hidden" name="tx_form_formframework[kontaktformular-50][__state]" value="TzozOToiVFlQTzNcQ01TXEZvcm1cRG9tYWluXFJ1bnRpbWVcRm9ybVN0YXRlIjoyOntzOjI1OiIAKgBsYXN0RGlzcGxheWVkUGFnZUluZGV4IjtpOjA7czoxMzoiACoAZm9ybVZhbHVlcyI7YTowOnt9fQ==1d9d97296996cb07f722d829563715ae20b1e425"&gt;&lt;input type="hidden" name="tx_form_formframework[__trustedProperties]" value="{&amp;quot;kontaktformular-50&amp;quot;:{&amp;quot;QP417ulHGiL2MCpgwFoU&amp;quot;:1,&amp;quot;singleselect-2&amp;quot;:1,&amp;quot;text-1&amp;quot;:1,&amp;quot;text-5&amp;quot;:1,&amp;quot;text-6&amp;quot;:1,&amp;quot;text-10&amp;quot;:1,&amp;quot;text-11&amp;quot;:1,&amp;quot;textarea-1&amp;quot;:1,&amp;quot;checkbox-1&amp;quot;:1,&amp;quot;__currentPage&amp;quot;:1}}107a6a59c816e0c73ea65ed9777a2afdb6758376"&gt;
&lt;/div&gt;

        &lt;input autocomplete="QP417ulHGiL2MCpgwFoU" aria-hidden="true" id="kontaktformular-50-QP417ulHGiL2MCpgwFoU" style="position:absolute; margin:0 0 0 -999em;" tabindex="-1" type="text" name="tx_form_formframework[kontaktformular-50][QP417ulHGiL2MCpgwFoU]"&gt;

**Comment by ohader** [comment]
That behavior in TYPO3v v11.4 was caused by a regression as described in https://forge.typo3.org/issues/95158 which has been reverted for v11.5 (final v11 LTS release).
