### ISSUE TITLE
Allow adding allowed values to existing attributes

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3/html-sanitizer#65]
I've come to code where custom `onclick` is added to `a`-Tags.
TYPO3 already ads an `onclick` to allow list for `a`-Tags.

I could not find any way to add another allowed value to the list.
Looks like the code is too robust to allow me to add or alter the already configured behaviour.
I only could remove the already build `a`-Tag and build it from scratch / from reading original values excluding the `onclick` and rebuilding it again?
Do I overlook something here? How should a developer use the library in such situation, where a framework already adds configuration?

That's our code which is just not called, because TYPO3 `onclick` value already does not match. Further values are not checked anymore. I couldn't find a way to check whether at least one value matches.
```php
class DefaultSanitizerBuilder extends Typo3DefaultSanitizerBuilder
{
    protected function createBasicTags(): array
    {
        $tags = parent::createBasicTags();
        // Allow onlick="econdaTrackMarker();" in addition to TYPO3 native onclick code.
        $tags['a']->getAttr('onclick')->addValues(new RegExpAttrValue('#^econdaTrackMarker\(#'));
        return $tags;
    }
}
```

**Comment by ohader** [comment]
@DanielSiepmann Looking forward to receiving your feedback on PR #66 (which makes mentioned core change above obsolete)

**Comment by AEHluis** [comment]
> Adding new `Tag::removeAttr($name)` and (maybe) `Attr::setFlags($flags)` methods to this library seems to be useful as well.

Do you have any idea if and when that will be added?
