### ISSUE TITLE
Problem: No email from my.typo3.org

### ISSUE THREAD

**Issue by Neustradamus** [TYPO3/html-sanitizer#75]
Dear @TYPO3, @TYPO3GmbH teams,

I have a problem, I do not received the lost password email from my.typo3.org.

My username is same than here.

Can you look?

Thanks in advance.

**Comment by ohader** [comment]
Please get in contact via email to info@typo3.com
(taken from https://my.typo3.org/faq/)

Besides that, there is not much I can do in the scope of this GitHub repository.
