### ISSUE TITLE
Add XMPP URI support (RFC5122)

### ISSUE THREAD

**Issue by Neustradamus** [TYPO3/html-sanitizer#76]
Dear @TYPO3, @TYPO3GmbH teams,

In first, I wish you a Happy New Year 2022!

Can you see for add XMPP URI support?
-> XMPP URI support must be added because there actually a problem, it is detected "mailto".

Examples:
- xmpp:username@domain.tld
- xmpp:username@domain.tld?message
- xmpp:mucroom@domain.tld?join

It is a standard:
- RFC5122: https://tools.ietf.org/html/rfc5122

Thanks in advance.

**Comment by ohader** [comment]
From the sanitizer part it should be possible to declare custom schemes (like `xmpp:`) already with https://github.com/TYPO3/html-sanitizer/blob/main/src/Behavior/Attr/UriAttrValueBuilder.php#L57-L62
I don't know (yet), what probably is missing on the TYPO3 core side.

I'll add test cases soon for `xmpp:` in particular to this library based on your provided examples.

**Comment by Neustradamus** [comment]
@ohader: Have you progressed on this ticket?

**Comment by ohader** [comment]
@Neustradamus Not yet, I did not find a good way to add arbitrary schemes (e.g. https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml) in a flexible way...

**Comment by ohader** [comment]
I checked IANA assignments and added some additional schemes. Unofficial URIs like `whatsapp:`, `tg:` etc. are supposed to be redirected through web APIs like `api.whatsapp.com` or `t.me`.

**Comment by Neustradamus** [comment]
@ohader: Thanks :)

In the test part, you have specify only "message" but all these cases will be good?
- xmpp:username@domain.tld
- xmpp:username@domain.tld?message
- xmpp:mucroom@domain.tld?join

**Comment by ohader** [comment]
The change allows using any value that stars with `xmpp:` in any `href` attribute. I don't think adding more tests is necessary here.

**Comment by Neustradamus** [comment]
@ohader: Thanks a lot for your improvements :)
