### ISSUE TITLE
that is not single

### ISSUE THREAD

**Issue by nenge123** [TYPO3/html-sanitizer#79]
need other Psr/src/log
![image](https://user-images.githubusercontent.com/16117315/177920487-12328bd6-7210-4022-8d4b-293d17d9fe1a.jpg)

**Comment by ohader** [comment]
The image you provided got access restricted & the description unfortunately does not provide much details here.
Feel free to reopen this issue, trying to describe the scenario and steps you've taken. Thanks for your understanding.
